DROP DATABASE IF EXISTS BDpractica2;
CREATE DATABASE IF NOT EXISTS BDpractica2;
USE BDpractica2;
CREATE TABLE Usuarios (
  id INT AUTO_INCREMENT,
  nombre_usuario VARCHAR(255) NOT NULL,
  correo VARCHAR(255) NOT NULL,
  contrasena VARCHAR(255) NOT NULL,
  imagen_perfil_url VARCHAR(300) NOT NULL,
  fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Usuario PRIMARY KEY (id),
  CONSTRAINT UQ_Usuario UNIQUE (nombre_usuario),
  CONSTRAINT UQ_Correo UNIQUE (correo)
);
CREATE TABLE Tareas (
  id INT AUTO_INCREMENT,
  usuario_id INT,
  titulo VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  completada BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Tarea PRIMARY KEY (id),
  CONSTRAINT FK_Tarea_Usuario FOREIGN KEY (usuario_id) REFERENCES Usuarios (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE Archivos (
  id INT AUTO_INCREMENT,
  usuario_id INT,
  nombre_archivo VARCHAR(255) NOT NULL,
  tipo_archivo VARCHAR(255) NOT NULL,
  url_archivo VARCHAR(255) NOT NULl,
  fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  fecha_modificacion DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_Archivo PRIMARY KEY (id),
  CONSTRAINT FK_Archivo_Usuario FOREIGN KEY (usuario_id) REFERENCES Usuarios (id) ON DELETE CASCADE ON UPDATE CASCADE
);