services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./nodejs-backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - /nodejs-backend/.env
